version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      # start the docker service
      - run: systemctl start docker
      # build the application image
      - run: docker build -t yasarui/react .
