version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:lts
        auth:
          username: yasarui
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      # build the application image
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t yasarui/react-nginx:$TAG .
          echo $$DOCKERHUB_PASSWORD | docker login -u $DOCKER_USER --password-stdin
          docker push yasarui/react-nginx:$TAG
